namespace SqrlNet.Crypto
{
	/// <summary>
	/// Interface for a pseudo random number generator.
	/// </summary>
	public interface ISqrlPseudoRandomNumberGenerator
	{
		/// <summary>
		/// Fills a byte array with randomly generated bytes.
		/// </summary>
		/// <param name='bytes'>
		/// The Bytes.
		/// </param>
		void GetBytes(byte[] bytes);
	}
}