using Sodium;

namespace SqrlNet.Crypto.Sodium
{
	/// <summary>
	/// Sodium pseudo random number generator.
	/// </summary>
	public class SodiumPseudoRandomNumberGenerator : ISqrlPseudoRandomNumberGenerator
	{
		#region ISqrlPseudoRandomNumberGenerator implementation

		/// <summary>
		///  Fills a byte array with randomly generated bytes. 
		/// </summary>
		/// <param name='bytes'>
		///  The Bytes. 
		/// </param>
		public void GetBytes(byte[] bytes)
		{
			bytes = SodiumCore.GetRandomBytes(bytes.Length);
		}

		#endregion
	}
}